version: "3.8"

services:
  nats:
    image: nats:latest
    command: 
      - "-c" 
      - "nats-server.conf"
      - "-js"
      - "--auth"
      - ${NATS_TOKEN}
    ports:
      - ${NATS_PORT}:4222
    networks:
      - nats-network
    restart: always
    volumes:
      - ./nats-server.conf:/nats-server.conf
      # - ./jetstream-data:/data

networks:
  nats-network:
    driver: bridge
    name: ${NATS_NETWORK_NAME}