serviceName: bank-service
http:
  port: :8000
  development: true
  httpClientDebug: true
  debugErrorsResponse: true
logger:
  level: debug
  devMode: false
  encoder: console
timeouts:
  mysqlInitMilliseconds: 1500
  mysqlInitRetryCount: 3
mysql:
  host: mysql_bank
  port: 3306 # if run in the same docker compose use  3306, but if run in difference docker compose use 3308 or follow .env file
  user: root
  password: adminpass123
  dbName: banks
  sslMode: false
nats:
  url: nats://passIsSecret@nats:4222
jwt:
  secret: secretIsSecretAndMustBeLong
  expire: 3600
  issuer: gobanking
  refreshExpire: 7200